### ISSUE TITLE
ARM builds for M1 macs

### ISSUE THREAD

**Issue by j-brown** [aerospike/aerospike-server-enterprise.docker#7]
Feature request: Multi arch builds for arch "linux/arm64/v8".
I know docker supports emulation on M1's for "linux/amd64" but having arm builds would be a great enhancement.

**Comment by kportertx** [comment]
Related: https://github.com/aerospike/aerospike-server/issues/19.

**Comment by ybogo** [comment]
Will official image will be provided for 6.2.x release?

**Comment by kportertx** [comment]
We are working with dockerhub to release the official images. In the meantime the images at [aerospike/aerospike-server-enterprise](https://hub.docker.com/r/aerospike/aerospike-server-enterprise/tags?page=1&name=6.2.0) are the same "bits" that the official images will have but we have more control of when they are released. The current blocker with dockerhub is that we had created a [`bootstrap.sh`](https://github.com/aerospike/aerospike-server.docker/blob/1799d0ef1303960ac423f9808c8d821f492b9e89/template/scripts/bootstrap.sh) script to improve debugging that is executed by the image build process which goes against their ["clarity" policy](https://github.com/docker-library/official-images/tree/6f8c8066b90e4f81d999d088f4081cc1723b2387#clarity).

Also we have moved the Dockerfile for enterprise to [aerospike/aerospike-server.docker](https://github.com/aerospike/aerospike-server.docker/) and will archive this repo soon.

**Comment by kportertx** [comment]
> :warning: **This repository has been archived and is no longer updated**.
> Please use the version at
> [aerospike/aerospike-server.docker](https://github.com/aerospike/aerospike-server.docker)
